spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: localhost:5052,localhost:5053,localhost:5054
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:5052,localhost:5053,localhost:5054
---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
---
  spring:
    profiles: prod
    kafka:
      producer:
        bootstrap-servers: prod:9092
        key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer